# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AppBundle, AdminBundle, FOSUserBundle, UserBundle]
    write_to:       %kernel.root_dir%/../web/
    #java: /usr/bin/java
    filters:
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss    
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery:
            inputs:
                 - '%kernel.root_dir%/../web/vendor/jquery/dist/jquery.min.js'
        light_box_js:
            inputs:
                - '%kernel.root_dir%/../web/vendor/lightbox2/dist/js/lightbox.min.js'
        light_box_css:
            inputs:
                - '%kernel.root_dir%/../web/vendor/lightbox2/dist/css/lightbox.css'
        validate_js:
            inputs:
                - '%kernel.root_dir%/../web/vendor/jquery-validation/dist/jquery.validate.min.js'
        validate_js_extra:
            input:
                - '%kernel.root_dir%/../web/vendor/jquery-validation/dist/additional-methods.min.js'        
        croppie_js:
            inputs:
                - '%kernel.root_dir%/../web/vendor/Croppie/croppie.min.js'
        croppie_css:
            inputs:
                - '%kernel.root_dir%/../web/vendor/Croppie/croppie.css'