admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin-panel

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation    

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}
    
oneup_uploader:
    resource: .
    type: uploader    
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"    
    
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml" 