imports:
    - { resource: parameters.yml }
    
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_AUTHOR: ROLE_USER
        ROLE_ADMIN: ROLE_AUTHOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
          dev:
              pattern: ^/(_(profiler|wdt)|css|images|js|translations)/
              security: false
          main:
              pattern: ^/
              form_login:
                  check_path: fos_user_security_check
                  login_path: fos_user_security_login
                  provider: fos_userbundle
                  csrf_token_generator: security.csrf.token_manager
              logout:
                path: fos_user_security_logout
                target: home_page
              anonymous: ~
              remember_me:
                  secret:   '%secret%'
                  lifetime: 2592000 # 1 month in seconds
                  path:     /
                  user_provider: fos_userbundle
                

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: ROLE_ADMIN }